## This generates bindings for the Box2D API
## 
## Note: Manually fix identity objects and null ids.
## 

discard """


const b2_nullWorldId*: b2WorldId = b2WorldId(index1: 0, revision: 0)
const b2_nullBodyId*: b2BodyId = b2BodyId(index1: 0, world0: 0, revision: 0)
const b2_nullShapeId*: b2ShapeId = b2ShapeId(index1: 0, world0: 0, revision: 0)
const b2_nullJointId*: b2JointId = b2JointId(index1: 0, world0: 0, revision: 0)
const b2_nullChainId*: b2ChainId = b2ChainId(index1: 0, world0: 0, revision: 0)
"""

import os, macros
import futhark
import paths, process


const outputPath = libraryRoot / "wrapper.nim"


const futharkCompilerArg {.define: "futharkCompilerArg".} = getClangIncludePath()


# Box2D API
importc:
    compilerArg futharkCompilerArg
    path box2dRoot / "include" / "box2d"
    outputPath outputPath
    renameCallback wrapperRenameCallback
    "base.h"
    "box2d.h"
    "collision.h"
    "id.h"
    "math_functions.h"
    "types.h"


processWrapperFile(outputPath, prefix="""
# This was generated by futhark, and should not be edited directly.

## This file should not be imported/included directly, instead import `box2d`_.
""")