name: Deploy docs


on:
    push:
        paths:
            - docs/**
            - src/**
            - nimdoc.cfg

jobs:
    deploy_docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - uses: jiro4989/setup-nim-action@v2
              name: Set up Nim
            
            - name: Build docs
              run: |
                sh ./build_docs.sh
            
            - uses: JamesIves/github-pages-deploy-action@v4
              name: Deploy docs to Pages
              with:
                folder: docs/htmldocs