on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    run_tests:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        
        runs-on: ${{ matrix.os }}
        
        steps:
            - uses: actions/checkout@v4
            
            - name: Init and update submodules 
              run: |
                git submodule init
                git submodule update
            
            - uses: jiro4989/setup-nim-action@v2
              name: Set up Nim
            
            - name: Build and run tests
              run: |
                nimble test -Y

  